# Generated by Django 4.2.1 on 2023-07-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rna_seq', '0006_delete_samplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_path', models.CharField(max_length=256)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.usermodel')),
            ],
        ),
    ]
