# Generated by Django 4.2.5 on 2023-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='batch_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
