# Generated by Django 4.2.5 on 2023-10-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rawdata_file_format_alter_rawdata_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
