# Generated by Django 4.2.5 on 2023-09-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rawdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('study_name', 'sample_name')},
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='batch_name',
            new_name='study_name',
        ),
    ]
