# Generated by Django 4.2.5 on 2023-10-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_sampleproject_sample_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleproject',
            name='sample_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='sample.samplefile'),
        ),
    ]
