# Generated by Django 4.2.5 on 2023-10-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_alter_sampleproject_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleproject',
            options={},
        ),
        migrations.AlterField(
            model_name='sampleproject',
            name='sample_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_projects', to='sample.samplefile'),
        ),
    ]
