# Generated by Django 4.2.5 on 2023-10-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_alter_sampleproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleproject',
            options={'ordering': ['project', 'sample_file']},
        ),
        migrations.AlterField(
            model_name='sampleproject',
            name='sample_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.samplefile'),
        ),
    ]
