# Generated by Django 4.2.6 on 2023-11-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0007_alter_project_sequencing_alter_task_project'),
        ('sample', '0011_alter_sampleproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_projects', to='rna_seq.project'),
        ),
        migrations.AlterField(
            model_name='sampleproject',
            name='sample_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='sample.samplefile'),
        ),
    ]
