# Generated by Django 4.2.5 on 2023-10-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rna_seq', '0005_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=56)),
                ('data_path', models.CharField(max_length=512)),
                ('data_source', models.CharField(choices=[('NCBI', 'NCBI'), ('ENSEMbL', 'ENSEMbL'), ('other', 'other')], default='NCBI', max_length=10)),
                ('metadata', models.CharField(blank=True, max_length=1256, null=True)),
            ],
            options={
                'ordering': ['specie', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('specie_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['specie_name'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('genome_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annot.genome')),
                ('file_format', models.CharField(choices=[('FQ', 'FASTQ'), ('FA', 'FASTA'), ('GBK', 'GBK'), ('BAT', 'BAT'), ('SAM', 'SAM'), ('BAM', 'BAM'), ('O', 'other')], max_length=10)),
                ('seq_type', models.CharField(choices=[('R', 'RNA'), ('D', 'DNA'), ('P', 'protein'), ('O', 'other')], max_length=10)),
            ],
            options={
                'ordering': ['specie', 'version', 'seq_type'],
            },
            bases=('annot.genome',),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.genome')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.project')),
            ],
            options={
                'ordering': ['genome', 'project'],
            },
        ),
        migrations.AddField(
            model_name='genome',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.specie'),
        ),
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together={('specie', 'version')},
        ),
    ]
