# Generated by Django 4.2.6 on 2023-10-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ('genome', 'file_name')},
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('genome', 'file_name')},
        ),
    ]
