# Generated by Django 4.2.1 on 2023-09-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0003_alter_task_task_name'),
        ('annot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.project')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.specie')),
            ],
            options={
                'ordering': ['project', 'specie'],
            },
        ),
    ]
