# Generated by Django 4.2.5 on 2023-10-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'ordering': ['group', 'organism_name']},
        ),
        migrations.RenameField(
            model_name='specie',
            old_name='specie_name',
            new_name='organism_name',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='specie',
            name='group',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='tax_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
