# Generated by Django 4.2.5 on 2023-09-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rna_seq', '0001_initial'),
        ('annot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.project'),
        ),
        migrations.AddField(
            model_name='reference',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.specie'),
        ),
        migrations.AddField(
            model_name='genome',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.specie'),
        ),
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together={('specie', 'version')},
        ),
    ]
