# Generated by Django 4.2.5 on 2023-10-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0002_alter_specie_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specie',
            old_name='tax_id',
            new_name='taxid',
        ),
    ]
