# Generated by Django 4.2.6 on 2023-10-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0002_alter_annotation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annots', to='annot.genome'),
        ),
    ]
