# Generated by Django 4.2.1 on 2023-09-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0002_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='data_path',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='reference',
            name='data_source',
            field=models.CharField(choices=[('NCBI', 'NCBI'), ('ENSEMbL', 'ENSEMbL'), ('other', 'other')], default='NCBI', max_length=10),
        ),
    ]
