# Generated by Django 4.2.5 on 2023-10-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0003_rename_tax_id_specie_taxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='data_source',
            field=models.CharField(choices=[('NCBI', 'NCBI'), ('ENSEMBL', 'ENSEMBL'), ('other', 'other')], default='NCBI', max_length=10),
        ),
    ]
