# Generated by Django 4.2.6 on 2023-10-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0004_alter_annotation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annot_type',
        ),
    ]
