# Generated by Django 4.2.5 on 2023-10-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0004_alter_genome_data_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['specie', 'assembly_version', 'seq_type']},
        ),
        migrations.AlterModelOptions(
            name='genome',
            options={'ordering': ['specie', 'assembly_version']},
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='version',
            new_name='assembly_version',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='data_path',
            new_name='ftp_path',
        ),
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together={('specie', 'assembly_version')},
        ),
    ]
