# Generated by Django 4.2.6 on 2023-11-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0005_remove_annotation_annot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annot_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('transcript', 'transcript'), ('protein', 'protein'), ('CDS', 'CDS'), ('RNA', 'RNA'), ('other', 'other')], default='other', max_length=24),
        ),
    ]
