# Generated by Django 4.2.6 on 2023-11-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0006_annotation_annot_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['genome', 'aligner']},
        ),
        migrations.AddField(
            model_name='reference',
            name='aligner',
            field=models.CharField(default='bowtie2', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='fa_path',
            field=models.CharField(default='ab', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='index_path',
            field=models.CharField(default='ab', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='annot.genome'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('genome', 'aligner')},
        ),
        migrations.RemoveField(
            model_name='reference',
            name='project',
        ),
    ]
