# Generated by Django 4.2.5 on 2023-10-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0007_alter_annotation_options_alter_genome_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together=set(),
        ),
    ]
