# Generated by Django 4.2.5 on 2023-10-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0008_alter_genome_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together={('specie', 'assembly_accession')},
        ),
    ]
