# Generated by Django 4.2.5 on 2023-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0009_alter_genome_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
