# Generated by Django 4.2.5 on 2023-10-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0010_genome_is_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['specie', 'version', 'seq_type']},
        ),
        migrations.AlterModelOptions(
            name='genome',
            options={'ordering': ['specie', 'version']},
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='assembly_accession',
            new_name='version',
        ),
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together={('specie', 'version')},
        ),
    ]
