# Generated by Django 4.2.6 on 2023-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0011_alter_annotation_options_alter_genome_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='local_path',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
    ]
