# Generated by Django 4.2.5 on 2023-09-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GAL', 'genome alignment'), ('DSA', 'DNA sequence alignment'), ('GAS', 'genome assembly'), ('CR', 'count reads'), ('TS', 'trim sequences'), ('QC', 'quality control'), ('CFF', 'convert file format')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=526, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.tool')),
            ],
            options={
                'ordering': ['method', 'tool'],
            },
        ),
    ]
