# Generated by Django 4.2.6 on 2023-11-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='exe_path',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='default_parameters',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='default parameters of the tool'),
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('tool_name', 'version')},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='download_url',
        ),
    ]
