# Generated by Django 4.2.5 on 2023-09-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['method_name', 'tool']},
        ),
        migrations.RenameField(
            model_name='method',
            old_name='method',
            new_name='method_name',
        ),
    ]
