# Generated by Django 4.2.5 on 2023-09-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_alter_method_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
