# Generated by Django 4.2.6 on 2023-11-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_alter_tool_tool_name_alter_tool_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['method_name']},
        ),
        migrations.RemoveField(
            model_name='method',
            name='id',
        ),
        migrations.RemoveField(
            model_name='method',
            name='tool',
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_name',
            field=models.CharField(max_length=96, primary_key=True, serialize=False),
        ),
    ]
