# Generated by Django 4.2.6 on 2023-11-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_alter_method_options_remove_method_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='commons.method')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='commons.tool')),
            ],
            options={
                'ordering': ['method', 'tool'],
            },
        ),
        migrations.CreateModel(
            name='MethodRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_methods', to='commons.method')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.method')),
            ],
            options={
                'ordering': ['method', 'child'],
            },
        ),
    ]
