version: "3"

# default connection is bridge rather than links
networks:
  web_network:
    driver: bridge

services:
  app:
    restart: always
    build: ./emirna_backend
    container_name: mirna-back
    command: bash -c "python3 erna/manage.py migrate && 
      python3 erna/manage.py makemigrations && 
      python3 erna/manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - ./emirna_backend:/code
    networks:
      - web_network

  vue_nginx:
    restart: always
    image: nginx:latest
    container_name: mirna-front
    ports:
      - "8080:8080"
    volumes:
      - ./emirna_frontend/dist/:/usr/share/nginx/html/ # vues dist
      - ./devops/nginx/conf:/etc/nginx/conf.d
      - ./devops/nginx/log:/var/log/nginx
    depends_on:
      - app
    networks:
      - web_network
    