# Generated by Django 4.2.5 on 2023-09-30 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='P00001', max_length=10, unique=True, verbose_name='project ID')),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=526)),
                ('status', models.CharField(choices=[('A', 'active'), ('D', 'deleted')], default='A', max_length=1)),
                ('sequencing', models.CharField(choices=[('M', 'mRNA-Seq'), ('MI', 'miRNA-Seq'), ('SC', 'scRNA-Seq'), ('O', 'Other')], default='M', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner identified by user_id')),
            ],
            options={
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10, unique=True, verbose_name='task ID')),
                ('task_name', models.CharField(blank=True, default='task name', max_length=100, verbose_name='task name')),
                ('params', models.CharField(blank=True, max_length=1256, verbose_name='parameters in json string')),
                ('input', models.CharField(blank=True, max_length=1256, verbose_name='input metadata in json string')),
                ('output', models.CharField(blank=True, max_length=1256, verbose_name='output metadata in json string')),
                ('is_ready', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.project')),
                ('tool', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commons.tool')),
            ],
            options={
                'ordering': ('project', 'task_id'),
                'unique_together': {('project', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='TaskTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_task', to='rna_seq.task')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='rna_seq.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_task', to='rna_seq.task')),
            ],
            options={
                'ordering': ('task',),
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'ready'), ('S', 'suspend'), ('E', 'running'), ('D', 'finished'), ('P', 'paused'), ('F', 'failed')], default='R', max_length=10)),
                ('command', models.CharField(max_length=5000, verbose_name='command for tool launching')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.task')),
            ],
            options={
                'ordering': ('task', 'id', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.project', verbose_name='Executed project identified by project_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='executor identified by user_id')),
            ],
            options={
                'ordering': ['project', 'user'],
            },
        ),
    ]
