# Generated by Django 4.2.1 on 2023-08-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktree',
            options={'ordering': ('task',)},
        ),
        migrations.RemoveField(
            model_name='tasktree',
            name='project',
        ),
        migrations.AlterField(
            model_name='tasktree',
            name='child',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_task', to='rna_seq.task'),
        ),
        migrations.AlterField(
            model_name='tasktree',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='rna_seq.task'),
        ),
    ]
