# Generated by Django 4.2.1 on 2023-07-09 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='task ID')),
                ('paramters', models.CharField(max_length=1256, verbose_name='parameters in json string')),
                ('input', models.CharField(max_length=1256, verbose_name='input metadata in json string')),
                ('output', models.CharField(max_length=1256, verbose_name='output metadata in json string')),
                ('is_ready', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.projectmodel')),
            ],
            options={
                'ordering': ('task_id',),
            },
        ),
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_path', models.CharField(max_length=256)),
                ('default_parameters', models.CharField(max_length=1000, verbose_name='default parameters of the tool')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('download_url', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_task', to='rna_seq.taskmodel')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='rna_seq.taskmodel')),
            ],
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.toolmodel'),
        ),
        migrations.CreateModel(
            name='TaskExecutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'suspend'), ('R', 'running'), ('D', 'finished'), ('F', 'failed')], max_length=10)),
                ('command', models.CharField(max_length=1256, verbose_name='command for tool launching')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.projectmanagermodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.taskmodel')),
            ],
            options={
                'ordering': ('task',),
            },
        ),
    ]
