# Generated by Django 4.2.1 on 2023-09-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('rna_seq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='task name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tool',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commons.tool'),
        ),
    ]
