# Generated by Django 4.2.5 on 2023-10-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0002_remove_task_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='input',
        ),
        migrations.RemoveField(
            model_name='task',
            name='output',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tool',
        ),
    ]
