# Generated by Django 4.2.1 on 2023-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0002_alter_tasktree_options_remove_tasktree_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktree',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_task', to='rna_seq.task'),
        ),
        migrations.AlterField(
            model_name='tasktree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='rna_seq.task'),
        ),
    ]
