# Generated by Django 4.2.1 on 2023-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0002_alter_task_task_name_alter_task_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, default='task name', max_length=100, verbose_name='task name'),
        ),
    ]
