# Generated by Django 4.2.5 on 2023-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=10, verbose_name='task ID'),
        ),
    ]
