# Generated by Django 4.2.1 on 2023-08-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0003_alter_tasktree_child_alter_tasktree_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'ordering': ('task',)},
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('R', 'ready'), ('S', 'suspend'), ('E', 'running'), ('D', 'finished'), ('P', 'paused'), ('F', 'failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.task'),
        ),
    ]
