# Generated by Django 4.2.1 on 2023-07-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0003_samplemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='taskexecutionmodel',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='taskexecutionmodel',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='tasktreemodel',
            name='child_task',
        ),
        migrations.RemoveField(
            model_name='tasktreemodel',
            name='parent_task',
        ),
        migrations.DeleteModel(
            name='ProjectManagerModel',
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
        migrations.DeleteModel(
            name='TaskExecutionModel',
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
        migrations.DeleteModel(
            name='TaskTreeModel',
        ),
        migrations.DeleteModel(
            name='ToolModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
