# Generated by Django 4.2.5 on 2023-10-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0004_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('project', 'task_id')},
        ),
    ]
