# Generated by Django 4.2.1 on 2023-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0004_alter_taskexecution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'ordering': ('task', 'start_time')},
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
