# Generated by Django 4.2.1 on 2023-07-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rna_seq', '0004_remove_projectmodel_owner_remove_samplemodel_creater_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('project_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='project ID')),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=526)),
            ],
            options={
                'ordering': ('project_id',),
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='task ID')),
                ('paramters', models.CharField(max_length=1256, verbose_name='parameters in json string')),
                ('input', models.CharField(max_length=1256, verbose_name='input metadata in json string')),
                ('output', models.CharField(max_length=1256, verbose_name='output metadata in json string')),
                ('is_ready', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.projectmodel')),
            ],
            options={
                'ordering': ('task_id',),
            },
        ),
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_path', models.CharField(max_length=256)),
                ('default_parameters', models.CharField(max_length=1000, verbose_name='default parameters of the tool')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('download_url', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='name of user')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'active'), ('R', 'revoke'), ('I', 'inactive')], max_length=10)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='TaskTreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_task', to='rna_seq.taskmodel')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='rna_seq.taskmodel')),
            ],
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.toolmodel'),
        ),
        migrations.CreateModel(
            name='TaskExecutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'suspend'), ('R', 'running'), ('D', 'finished'), ('F', 'failed')], max_length=10)),
                ('command', models.CharField(max_length=1256, verbose_name='command for tool launching')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.projectmanagermodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.taskmodel')),
            ],
            options={
                'ordering': ('task',),
            },
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_path', models.CharField(max_length=256)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.usermodel', verbose_name='owner identified by user_id'),
        ),
        migrations.AddField(
            model_name='projectmanagermodel',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.usermodel', verbose_name='executor identified by user_id'),
        ),
        migrations.AddField(
            model_name='projectmanagermodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.projectmodel', verbose_name='Executed project identified by project_id'),
        ),
    ]
