# Generated by Django 4.2.1 on 2023-07-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
