# Generated by Django 4.2.1 on 2023-08-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0005_alter_taskexecution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('R', 'ready'), ('S', 'suspend'), ('E', 'running'), ('D', 'finished'), ('P', 'paused'), ('F', 'failed')], default='R', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.task'),
        ),
    ]
