# Generated by Django 4.2.6 on 2023-11-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0006_alter_taskexecution_status_alter_taskexecution_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sequencing',
            field=models.CharField(choices=[('M', 'mRNA-Seq'), ('MI', 'miRNA-Seq'), ('SC', 'scRNA-Seq'), ('O', 'Other')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rna_seq.project'),
        ),
    ]
