# Generated by Django 4.2.1 on 2023-08-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0006_alter_taskexecution_status_alter_taskexecution_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'ordering': ('task', 'id', 'start_time')},
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='command',
            field=models.CharField(max_length=5000, verbose_name='command for tool launching'),
        ),
    ]
