# Generated by Django 4.2.6 on 2023-11-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0008_method_tool_methodrelation_methodtool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='default_parameters',
            new_name='default_params',
        ),
    ]
