# Generated by Django 4.2.6 on 2023-11-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0010_alter_methodtool_method_alter_methodtool_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rna_seq.method'),
        ),
    ]
