# Generated by Django 4.2.6 on 2023-11-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0011_alter_methodrelation_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodtool',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='rna_seq.tool'),
        ),
    ]
