# Generated by Django 4.2.6 on 2023-11-06 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0012_alter_methodtool_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=128)),
                ('next_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='rna_seq.methodtool')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rna_seq.methodtool')),
            ],
            options={
                'ordering': ['pipeline_name', 'step'],
            },
        ),
    ]
