# Generated by Django 4.2.6 on 2023-11-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0014_alter_pipeline_next_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='method_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method_tools', to='rna_seq.methodtool'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sequencing',
            field=models.CharField(choices=[('mrna-seq', 'mRNA-Seq'), ('mirna-seq', 'miRNA-Seq'), ('scrna-seq', 'scRNA-Seq'), ('other', 'other')], default='mrna-seq', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='task name'),
        ),
    ]
