# Generated by Django 4.2.6 on 2023-11-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0015_task_method_tool_alter_project_sequencing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rna_seq.project', verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=10, verbose_name='Task ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Task Name'),
        ),
    ]
