# Generated by Django 4.2.6 on 2023-11-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0016_alter_task_project_alter_task_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='method_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rna_seq.methodtool'),
        ),
    ]
